# Generated by Django 4.0.1 on 2022-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorca', models.DecimalField(blank=True, db_column='CODIGORCA', decimal_places=0, max_digits=4, null=True)),
                ('codigosv', models.DecimalField(blank=True, db_column='CODIGOSV', decimal_places=0, max_digits=4, null=True)),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=80, null=True)),
                ('metavenda', models.DecimalField(blank=True, db_column='METAVENDA', decimal_places=2, max_digits=13, null=True)),
                ('venda', models.DecimalField(blank=True, db_column='VENDA', decimal_places=2, max_digits=65, null=True)),
                ('meta_pos', models.DecimalField(blank=True, db_column='META_POS', decimal_places=0, max_digits=11, null=True)),
                ('pos', models.BigIntegerField(blank=True, db_column='POS', null=True)),
                ('qt_cupons', models.IntegerField(blank=True, db_column='QT_CUPONS', null=True)),
            ],
            options={
                'db_table': 'APP_CUPONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppLogin',
            fields=[
                ('codigorca', models.DecimalField(db_column='CODIGORCA', decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('nomerca', models.CharField(db_column='NOMERCA', max_length=40)),
                ('codigosv', models.DecimalField(db_column='CODIGOSV', decimal_places=0, max_digits=4)),
                ('nomesv', models.CharField(db_column='NOMESV', max_length=40)),
                ('codigocv', models.DecimalField(blank=True, db_column='CODIGOCV', decimal_places=0, max_digits=4, null=True)),
                ('nomecv', models.CharField(blank=True, db_column='NOMECV', max_length=40, null=True)),
                ('modelo', models.CharField(blank=True, db_column='MODELO', max_length=16, null=True)),
                ('faixa', models.CharField(blank=True, db_column='FAIXA', max_length=14, null=True)),
                ('senha', models.CharField(blank=True, db_column='SENHA', max_length=5, null=True)),
                ('funcao', models.CharField(blank=True, db_column='FUNCAO', max_length=13, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True)),
            ],
            options={
                'db_table': 'APP_LOGIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppMatinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codsuperv', models.IntegerField(blank=True, db_column='CODSUPERV', null=True)),
                ('codrca', models.IntegerField(blank=True, db_column='CODRCA', null=True)),
                ('rca', models.CharField(blank=True, db_column='RCA', max_length=60, null=True)),
                ('clicad', models.IntegerField(blank=True, db_column='CLICAD', null=True)),
                ('cliativos', models.IntegerField(blank=True, db_column='CLIATIVOS', null=True)),
                ('metavenda', models.FloatField(blank=True, db_column='METAVENDA', null=True)),
                ('venda', models.FloatField(blank=True, db_column='VENDA', null=True)),
                ('metapos', models.IntegerField(blank=True, db_column='METAPOS', null=True)),
                ('positivacao', models.IntegerField(blank=True, db_column='POSITIVACAO', null=True)),
            ],
            options={
                'db_table': 'APP_MATINAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppMetageral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('nivel', models.CharField(blank=True, db_column='NIVEL', max_length=5, null=True)),
                ('codigorca', models.IntegerField(blank=True, db_column='CODIGORCA', null=True)),
                ('meta', models.DecimalField(blank=True, db_column='META', decimal_places=2, max_digits=65, null=True)),
            ],
            options={
                'db_table': 'APP_METAGERAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppSamuraicupom',
            fields=[
                ('codigorca', models.IntegerField(db_column='CODIGORCA', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('categoria', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='CATEGORIA', max_length=196, null=True)),
                ('metavenda', models.IntegerField(blank=True, db_column='METAVENDA', null=True)),
                ('venda', models.DecimalField(blank=True, db_column='VENDA', decimal_places=2, max_digits=65, null=True)),
                ('percvenda', models.DecimalField(blank=True, db_column='PERCVENDA', decimal_places=2, max_digits=65, null=True)),
                ('metapos', models.IntegerField(blank=True, db_column='METAPOS', null=True)),
                ('pos', models.IntegerField(blank=True, db_column='POS', null=True)),
                ('percpos', models.DecimalField(blank=True, db_column='PERCPOS', decimal_places=2, max_digits=65, null=True)),
                ('qt_cupons', models.IntegerField(blank=True, db_column='QT_CUPONS', null=True)),
            ],
            options={
                'db_table': 'APP_SAMURAICUPOM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowMeta',
            fields=[
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('codcv', models.IntegerField(blank=True, db_column='CODCV', null=True)),
                ('codsv', models.IntegerField(blank=True, db_column='CODSV', null=True)),
                ('codigorca', models.IntegerField(db_column='CODIGORCA', primary_key=True, serialize=False)),
                ('codfornec', models.IntegerField(blank=True, db_column='CODFORNEC', null=True)),
                ('fornecedor', models.CharField(blank=True, db_column='FORNECEDOR', max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=30, null=True)),
                ('metavalor', models.IntegerField(blank=True, db_column='METAVALOR', null=True)),
                ('metapositivacao', models.IntegerField(blank=True, db_column='METAPOSITIVACAO', null=True)),
            ],
            options={
                'db_table': 'SHOW_META',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowRca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorca', models.IntegerField(db_column='CODIGORCA')),
                ('nomerca', models.CharField(db_column='NOMERCA', max_length=60)),
                ('codsv', models.IntegerField(db_column='CODSV')),
                ('nomesv', models.CharField(db_column='NOMESV', max_length=60)),
                ('codcv', models.IntegerField(db_column='CODCV')),
                ('nomecv', models.CharField(db_column='NOMECV', max_length=60)),
                ('modelo', models.CharField(db_column='MODELO', max_length=60)),
                ('faixa', models.CharField(db_column='FAIXA', max_length=60)),
                ('senha', models.CharField(db_column='SENHA', max_length=128)),
            ],
            options={
                'db_table': 'SHOW_RCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField(blank=True, db_column='CODCLI', null=True)),
                ('cliente', models.CharField(blank=True, db_column='CLIENTE', max_length=255, null=True)),
                ('fantasia', models.CharField(blank=True, db_column='FANTASIA', max_length=255, null=True)),
                ('codrca', models.IntegerField(blank=True, db_column='CODRCA', null=True)),
                ('foto', models.CharField(blank=True, db_column='FOTO', max_length=255, null=True)),
                ('recebido', models.CharField(blank=True, db_column='RECEBIDO', max_length=5, null=True)),
            ],
            options={
                'db_table': 'SHOW_REVISTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
                ('codcv', models.IntegerField(blank=True, db_column='CODCV', null=True)),
                ('codsv', models.IntegerField(db_column='CODSV')),
                ('codigorca', models.IntegerField(blank=True, db_column='CODIGORCA', null=True)),
                ('codigofornecedor', models.IntegerField(blank=True, db_column='CODIGOFORNECEDOR', null=True)),
                ('fornecedor', models.CharField(blank=True, db_column='FORNECEDOR', max_length=60, null=True)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=80, null=True)),
                ('codigocliente', models.IntegerField(db_column='CODIGOCLIENTE')),
                ('valor', models.DecimalField(blank=True, db_column='VALOR', decimal_places=2, max_digits=65, null=True)),
            ],
            options={
                'db_table': 'SHOW_VENDA',
                'managed': False,
            },
        ),
    ]
